set(DSPCORE_CORE_HEADERS
    "${CMAKE_CURRENT_LIST_DIR}/Version.h")
set(DSPCORE_CORE_SOURCES
    "${CMAKE_CURRENT_LIST_DIR}/Version.cpp")

target_sources(DspCore PRIVATE ${DSPCORE_CORE_HEADERS} ${DSPCORE_CORE_SOURCES})
dspcore_stage_headers(${DSPCORE_CORE_HEADERS})
dspcore_add_dox(
    ${DSPCORE_CORE_HEADERS}
    "${CMAKE_CURRENT_LIST_DIR}/Core.dox")

install(FILES ${DSPCORE_CORE_HEADERS}
    DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}/DspCore/Core"
    CONFIGURATIONS Release)
