#!/bin/sh

DSPCORE_SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
DSPCORE_ROOT=$(CDPATH= cd -- "$DSPCORE_SCRIPT_DIR/.." && pwd)
DSPCORE_BUILD_ROOT="$DSPCORE_ROOT/build"
DSPCORE_DIST_ROOT="$DSPCORE_ROOT/dist"
DSPCORE_ROMODULAR_SCRIPTS="$DSPCORE_ROOT/tools/RoModularBuild/scripts"

if [ ! -f "$DSPCORE_ROMODULAR_SCRIPTS/common.sh" ]; then
    printf '%s\n' \
        "error: RoModularBuild is unavailable; initialize tools/RoModularBuild with git submodule update --init --recursive" \
        >&2
    exit 2
fi

ROMODULAR_PROJECT_ROOT=$DSPCORE_ROOT
ROMODULAR_BUILD_ROOT=$DSPCORE_BUILD_ROOT
ROMODULAR_DIST_ROOT=$DSPCORE_DIST_ROOT
ROMODULAR_PROJECT_LABEL=DspCore
ROMODULAR_CONFIGURE_COMMAND=scripts/configure.sh
ROMODULAR_DEFAULT_CONFIGURATION=Debug
ROMODULAR_DOCUMENTATION_PRESET=documentation
ROMODULAR_DOCUMENTATION_CONFIGURATION=Release
ROMODULAR_INSTALL_CONFIGURATION=Release
ROMODULAR_TESTING_CACHE_ARGUMENT=-DDSPCORE_TESTING=ON
ROMODULAR_EXAMPLES_CACHE_ARGUMENT=-DDSPCORE_EXAMPLES=ON

export \
    ROMODULAR_PROJECT_ROOT \
    ROMODULAR_BUILD_ROOT \
    ROMODULAR_DIST_ROOT \
    ROMODULAR_PROJECT_LABEL \
    ROMODULAR_CONFIGURE_COMMAND \
    ROMODULAR_DEFAULT_CONFIGURATION \
    ROMODULAR_DOCUMENTATION_PRESET \
    ROMODULAR_DOCUMENTATION_CONFIGURATION \
    ROMODULAR_INSTALL_CONFIGURATION \
    ROMODULAR_TESTING_CACHE_ARGUMENT \
    ROMODULAR_EXAMPLES_CACHE_ARGUMENT
