set(DSPCORE_SRC_DIRECTORY "${CMAKE_CURRENT_LIST_DIR}")

add_library(DspCore STATIC)
add_library(DspCore::DspCore ALIAS DspCore)

target_compile_features(DspCore PUBLIC cxx_std_${DSPCORE_REQUIRED_CXX_STANDARD})
target_link_libraries(DspCore PUBLIC Foundation::Foundation)

set(DSPCORE_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/artifacts")
set_target_properties(DspCore PROPERTIES
    ARCHIVE_OUTPUT_DIRECTORY "${DSPCORE_OUTPUT_DIRECTORY}/lib"
    ARCHIVE_OUTPUT_DIRECTORY_DEBUG "${DSPCORE_OUTPUT_DIRECTORY}/lib"
    ARCHIVE_OUTPUT_DIRECTORY_RELEASE "${DSPCORE_OUTPUT_DIRECTORY}/lib"
    LIBRARY_OUTPUT_DIRECTORY "${DSPCORE_OUTPUT_DIRECTORY}/lib"
    LIBRARY_OUTPUT_DIRECTORY_DEBUG "${DSPCORE_OUTPUT_DIRECTORY}/lib"
    LIBRARY_OUTPUT_DIRECTORY_RELEASE "${DSPCORE_OUTPUT_DIRECTORY}/lib"
    RUNTIME_OUTPUT_DIRECTORY "${DSPCORE_OUTPUT_DIRECTORY}/bin"
    RUNTIME_OUTPUT_DIRECTORY_DEBUG "${DSPCORE_OUTPUT_DIRECTORY}/bin"
    RUNTIME_OUTPUT_DIRECTORY_RELEASE "${DSPCORE_OUTPUT_DIRECTORY}/bin"
    OUTPUT_NAME "DspCore"
    DEBUG_POSTFIX "_d")

set(DSPCORE_BUILD_INCLUDE_DIR
    "${CMAKE_BINARY_DIR}/include/DspCore-${PROJECT_VERSION}")

set(DSPCORE_TOP_LEVEL_HEADERS
    "${CMAKE_CURRENT_LIST_DIR}/DspCore.h"
    "${CMAKE_CURRENT_LIST_DIR}/DspCore_BuildSettings.h")

if(DSPCORE_CORE)
    list(APPEND DSPCORE_TOP_LEVEL_HEADERS
        "${CMAKE_CURRENT_LIST_DIR}/DspCore_Core.h")
endif()

target_sources(DspCore PRIVATE
    "${CMAKE_CURRENT_LIST_DIR}/DspCore.cpp"
    ${DSPCORE_TOP_LEVEL_HEADERS})

target_include_directories(DspCore
    PUBLIC
        $<BUILD_INTERFACE:${DSPCORE_BUILD_INCLUDE_DIR}>
        $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>)

dspcore_stage_headers(${DSPCORE_TOP_LEVEL_HEADERS})
dspcore_add_dox(
    ${DSPCORE_TOP_LEVEL_HEADERS}
    "${CMAKE_CURRENT_LIST_DIR}/DspCoreTop.dox")

if(DSPCORE_CORE)
    dspcore_add_macro(PUBLIC DSPCORE_CORE)
endif()

if(DSPCORE_CORE)
    add_subdirectory(DspCore)
endif()

install(TARGETS DspCore
    EXPORT DspCoreTargets
    CONFIGURATIONS Release
    ARCHIVE DESTINATION "${CMAKE_INSTALL_LIBDIR}"
    LIBRARY DESTINATION "${CMAKE_INSTALL_LIBDIR}"
    RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}"
    INCLUDES DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}")

install(FILES ${DSPCORE_TOP_LEVEL_HEADERS}
    DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}"
    CONFIGURATIONS Release)

install(EXPORT DspCoreTargets
    FILE DspCoreTargets.cmake
    NAMESPACE DspCore::
    DESTINATION "${CMAKE_INSTALL_LIBDIR}/cmake/DspCore"
    CONFIGURATIONS Release)
